# Generated by Django 5.2.5 on 2025-08-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('conhecidoPor', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1)),
                ('escolaridade', models.CharField(blank=True, choices=[('nao_informado', 'Não informado'), ('analfabeto', 'Analfabeto'), ('fundamental', 'Ensino Fundamental'), ('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('medio', 'Ensino Médio'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('superior', 'Ensino Superior'), ('superior_incompleto', 'Ensino Superior Incompleto'), ('pos_graduacao', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('pos_doutorado', 'Pós-Doutorado')], max_length=30, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pessoas',
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='unique_cpf_when_filled')],
            },
        ),
    ]
