# Generated by Django 5.2.5 on 2025-09-09 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='uuid',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
