# Generated by Django 5.2.5 on 2025-09-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_pessoa_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nascimento',
            new_name='dataNascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='estado_civil',
            new_name='estadoCivil',
        ),
    ]
