# Generated by Django 5.2.5 on 2025-10-29 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_rename_data_nascimento_pessoa_datanascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='uuid',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
